name: breath_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  build_runner: ^2.10.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed: ^3.2.3
  go_router: ^17.0.0
  intro_slider: ^4.2.5
  json_serializable: ^6.11.2
  mocktail: ^1.0.4
  shared_preferences: ^2.5.4

dev_dependencies:
  custom_lint: ^0.8.1
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  riverpod_lint: ^3.0.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
